In [5]:
import numpy as np

def softmax(x,axis = -1):
    # A stable softmax implementation
    x_exp = np.exp(x-np.max(x,axis = axis,keepdims=True))
    return x_exp/np.sum(x_exp,axis=axis,keepdims=True)
N= 5
d_model = 64
d_k = d_model
d_v = d_model

X= np.random.randn(N,d_model)

w_q = np.random.randn(d_model,d_k)
w_k = np.random.randn(d_model,d_k)
w_v = np.random.randn(d_model,d_v)

Q = X @ w_q
K = X @ w_k
V =  X @ w_v
scores = Q @K.T 
Scores = scores / np.sqrt(d_k)
alpha = softmax(scores,axis = -1)
O = alpha @ V
print("O: ",O)


O:  [[ -1.23826956   0.07747621  17.81223672  11.56557941  -8.82581245
   -1.13811448   4.25674557  -7.46771085   2.93176995  -4.08431988
    4.72081557   4.36332658   2.99584607   3.13770691  -4.85539579
   -7.67867595   6.82806378   4.52587056  -3.20496693  14.29749462
    4.70214143   5.59831871   0.77710384  14.54263005   0.16760284
    1.53385547 -10.10661732   7.02735325  -6.20206832   7.23629931
    8.32768967   2.02025036  -6.93108872   0.54713999  -4.44973883
    3.37399478  -2.50405665  -4.86458285  -0.22296761  -1.80498526
   -1.42521367  -3.37264498   8.712712    -0.64102194  -5.81951691
   -5.61895375  -3.35348339  -3.50450935  -2.26362697   3.61296951
   -2.37159262  -5.86275331  20.21079113  -2.65360329 -13.80792476
   -5.88610998   2.24111857   9.21440595   8.45711491  11.14486441
   -5.83145749  -8.90506286  -2.42072861   6.89246463]
 [  3.03786578  -0.26647146   2.42499108   1.73755832 -17.0608079
    0.23949459   6.36872482  -4.2970279   -6.58313922 -10.20125511
    

In [6]:
print("Alpha: ",alpha)


Alpha:  [[0.00000000e+000 9.45650096e-086 1.00000000e+000 9.60183213e-275
  0.00000000e+000]
 [1.16653930e-283 0.00000000e+000 4.85986748e-197 1.00000000e+000
  4.00603445e-049]
 [3.18373219e-199 1.53871186e-012 2.73342525e-075 2.28113045e-145
  1.00000000e+000]
 [3.38424024e-019 2.52270467e-075 0.00000000e+000 9.76776289e-124
  1.00000000e+000]
 [0.00000000e+000 1.12591815e-192 0.00000000e+000 1.00000000e+000
  0.00000000e+000]]


In [7]:
print("Scores: ",Scores)

Scores:  [[-59.68507372  41.64792342  66.11987537 -12.74874296 -51.08829146]
 [-26.30565118 -43.39378301  -1.37449022  55.1290413   41.19918283]
 [ 39.71352647  93.44556445  75.38453307  55.21430297  96.84557388]
 [ 44.01083272  27.85601234 -54.78599183  13.92189813  49.32708113]
 [-95.67241659  11.14324033 -89.25704418  66.3904577  -29.38933839]]
