In [1]:
import tensorflow as tf
import numpy as np

In [2]:
print(tf.__version__)

2.21.0


In [3]:
# Different data structure => 0D, 1D, 2D more than 2
a = tf.constant(5)
a

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [4]:

b = tf.constant([1,2,3,4])
b # Vector are 1D

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [5]:
c = tf.constant([[1,2,3],
                 [4,5,6]])
c

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [6]:
d = tf.constant([[[1,3,4],[34,12,1],[5,6,7]],[[1,3,4],[34,12,1],[5,6,7]]])
d 

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  3,  4],
        [34, 12,  1],
        [ 5,  6,  7]],

       [[ 1,  3,  4],
        [34, 12,  1],
        [ 5,  6,  7]]], dtype=int32)>

### Different operation

In [7]:
a = tf.constant([1,2])
b = tf.constant([3,4])
a,b

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>)

In [8]:
# Sum operation
ResSum = tf.add(a,b)
ResSum

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

In [9]:
# Subtract peration
Sub = tf.subtract(a,b)
Sub

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-2, -2], dtype=int32)>

In [10]:
# The multiplication 
ev = tf.multiply(a,b)
ev

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 8], dtype=int32)>

In [11]:
a_1 = tf.constant([[1,2],[4,3]])
b_1 = tf.constant([[4,3],[8,7]])
mm = tf.matmul(a_1,b_1)
mm

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [40, 33]], dtype=int32)>

In [12]:
# Division 
a,b

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>)

In [13]:
division = tf.divide(a_1,b_1) # To tensorflow the number/0 is infinit
division

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.25      , 0.66666667],
       [0.5       , 0.42857143]])>

In [14]:
d1 = tf.constant([[1,2],[10000,1]])
d2 = tf.constant([[0,1],[0,4]])
div = tf.divide(d1,d2)

In [15]:
div

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ inf, 2.  ],
       [ inf, 0.25]])>

# Broadcasting

In [16]:
ab = tf.constant([1,2,4])
bb = tf.constant(4)
mult_broad = ab * bb
mult_broad

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4,  8, 16], dtype=int32)>

In [17]:
ab = tf.constant([1,2,4])
bb = tf.constant(4)
rev_broad = bb *ab
rev_broad

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4,  8, 16], dtype=int32)>

In [18]:
sumBro = ab+bb
sumBro

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 6, 8], dtype=int32)>

In [19]:
subbro = ab-bb
subbro

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-3, -2,  0], dtype=int32)>

## Reshape

In [20]:
a= tf.constant([1,2,3,0.4,5,6,7,8])
a.shape

TensorShape([8])

In [21]:
b = tf.reshape(a,shape=(2,2,2))

In [22]:
b

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[1. , 2. ],
        [3. , 0.4]],

       [[5. , 6. ],
        [7. , 8. ]]], dtype=float32)>

# Add dimenction

In [23]:
b0 = tf.expand_dims(a,0)
b0

<tf.Tensor: shape=(1, 8), dtype=float32, numpy=array([[1. , 2. , 3. , 0.4, 5. , 6. , 7. , 8. ]], dtype=float32)>

In [24]:
bMins1 = tf.expand_dims(a,-1)
bMins1

<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[1. ],
       [2. ],
       [3. ],
       [0.4],
       [5. ],
       [6. ],
       [7. ],
       [8. ]], dtype=float32)>

In [25]:
b1 = tf.expand_dims(a,1)
b1

<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[1. ],
       [2. ],
       [3. ],
       [0.4],
       [5. ],
       [6. ],
       [7. ],
       [8. ]], dtype=float32)>

In [26]:
bMins1 == b1

<tf.Tensor: shape=(8, 1), dtype=bool, numpy=
array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])>

In [27]:
bMins1 == b0

<tf.Tensor: shape=(8, 8), dtype=bool, numpy=
array([[ True, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False,  True, False, False, False],
       [False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False,  True]])>

In [28]:
bMins1 , b0

(<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
 array([[1. ],
        [2. ],
        [3. ],
        [0.4],
        [5. ],
        [6. ],
        [7. ],
        [8. ]], dtype=float32)>,
 <tf.Tensor: shape=(1, 8), dtype=float32, numpy=array([[1. , 2. , 3. , 0.4, 5. , 6. , 7. , 8. ]], dtype=float32)>)

In [29]:
# Square 
s = tf.square(a)
s


<tf.Tensor: shape=(8,), dtype=float32, numpy=
array([ 1.        ,  4.        ,  9.        ,  0.16000001, 25.        ,
       36.        , 49.        , 64.        ], dtype=float32)>

In [30]:
a == s/a

<tf.Tensor: shape=(8,), dtype=bool, numpy=array([ True,  True,  True, False,  True,  True,  True,  True])>

In [31]:
C = tf.sqrt(s)
C

<tf.Tensor: shape=(8,), dtype=float32, numpy=array([1. , 2. , 3. , 0.4, 5. , 6. , 7. , 8. ], dtype=float32)>