# Matrics operation

In [12]:
# Import libraries
import tensorflow as tf
import tkinter as tk

In [2]:
a = tf.constant([[3,4],[9,8],[5,3]],dtype= float)
a

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[3., 4.],
       [9., 8.],
       [5., 3.]], dtype=float32)>

In [3]:
a_Square = tf.square(a)
a_Square

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 9., 16.],
       [81., 64.],
       [25.,  9.]], dtype=float32)>

In [4]:
# Sqrt 
a_sqrt = tf.sqrt(a)

In [5]:
a_sqrt

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1.7320508, 2.       ],
       [3.       , 2.828427 ],
       [2.236068 , 1.7320508]], dtype=float32)>

# Min, Max, Median, STD
 

In [6]:
am = tf.constant([[1,2,4,5],[9,0,8,7]],dtype = float)
min = tf.reduce_min(am)
min

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [7]:
# Max 
max = tf.reduce_max(am,axis= None)
print(am)
print(max)

tf.Tensor(
[[1. 2. 4. 5.]
 [9. 0. 8. 7.]], shape=(2, 4), dtype=float32)
tf.Tensor(9.0, shape=(), dtype=float32)


In [8]:
# Mean 
mean = tf.reduce_mean(am)
mean.numpy()

np.float32(4.5)

In [9]:
sum = tf.reduce_sum(am)
sum

<tf.Tensor: shape=(), dtype=float32, numpy=36.0>

In [10]:
# Standard division 
std = tf.math.reduce_std(am)
print(std)
print(f"STD: {std:.2f}")


tf.Tensor(3.122499, shape=(), dtype=float32)
STD: 3.12


In [11]:
# Sum 
sum = tf.reduce_sum(am)
print("SUM: ",sum)

SUM:  tf.Tensor(36.0, shape=(), dtype=float32)
